package com.example.akkar2.entities;

public enum DriverLocation {
    ARIANA,BEJA,BENAROUS,BIZERTE,GABES,GAFSA,JENDOUBA,KAIROUAN,KASSERINE,KEBILI,LEKEF,MAHDIA,MANOUBA,MEDENINE,
    MONASTIR,NABEUL,SFAX,SIDIBOUZID,SILIANA,SOUSSE,TATAOUINE,TOZEUR,TUNIS,ZAGHOUAN
    }
